#!/bin/bash

cd /

while :
do

# Select language
function lang_clear_cache() {
	# Clear cache
	rm -rf "/opt/regataos-help/scripts/function-scripts"
	rm -rf "/opt/regataos-help/www/js/translations/language"
}

function lang_pt_BR() {
	ln -sf /opt/regataos-help/scripts/pt-br /opt/regataos-help/scripts/function-scripts
	ln -sf /opt/regataos-help/www/js/translations/pt-br /opt/regataos-help/www/js/translations/language
}

function lang_pt_PT() {
	ln -sf /opt/regataos-help/scripts/pt-br /opt/regataos-help/scripts/function-scripts
	ln -sf /opt/regataos-help/www/js/translations/pt-br /opt/regataos-help/www/js/translations/language
}

function lang_en_US() {
	ln -sf /opt/regataos-help/scripts/en-us /opt/regataos-help/scripts/function-scripts
	ln -sf /opt/regataos-help/www/js/translations/en-us /opt/regataos-help/www/js/translations/language
}

user=$(users | awk '{print $1}')
if test -e "/home/$user/.config/plasma-localerc" ; then
	lang=$(grep -r LANG "/home/$user/.config/plasma-localerc")

	if [[ $lang == *"pt_BR"* ]]; then
		lang_clear_cache
		lang_pt_BR

	elif [[ $lang == *"pt_PT"* ]]; then
		lang_clear_cache
		lang_pt_PT

	elif [[ $lang == *"en_US"* ]]; then
		lang_clear_cache
		lang_en_US

	else
		lang_clear_cache
		lang_en_US
	fi

	break
else
	if test -e "/home/$user/.config/user-dirs.locale" ; then
		lang=$(cat "/home/$user/.config/user-dirs.locale")

		if [[ $lang == *"pt_BR"* ]]; then
			lang_clear_cache
			lang_pt_BR

		elif [[ $lang == *"pt_PT"* ]]; then
			lang_clear_cache
			lang_pt_PT

		elif [[ $lang == *"en_US"* ]]; then
			lang_clear_cache
			lang_en_US

		else
			lang_clear_cache
			lang_en_US
		fi

		break
	fi
fi

   sleep 1
done
